version: '3'

services:
  app:
    build: ./docker
    container_name: desafio-pfa
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s java -jar /application/desafio-0.1-all.jar
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db-network
      - server
  
  nginx:
    build: ./docker/nginx
    restart: always
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - server
  
  db:
    image: mysql:5.7
    container_name: mysql
    command: "--innodb-use-native-aio=0"
    restart: always
    tty: true
    networks:
      - db-network
    volumes:
      - ./dbdata/data:/var/lib/mysql
      - ./dbdata/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root

networks:
  db-network:
    driver: bridge
  server:
    driver: bridge